name = str(input("What is your name? "))
age = int(input("What is your age? "))
contact = str(input("What is your contact number? "))
degree = str(input("What is your degree? "))
hobby = str(input("What is your hobby? "))
siblings = int(input("How many siblings do you have? "))
friendname = str(input("What is your best friend's name? "))
activecourse = str(input("What is your active course? "))
favlanguage = str(input("What is your favorite programming language? "))
strength = str(input("What is your strength? "))
weakness = str(input("What is your weakness? "))
business = str(input("What is your business? "))
favoritefood = str(input("What is your favorite food? "))
favsubject = str(input("What is your favorite subject? "))
career = str(input("What is your career? "))
gpa = float(input("What is your GPA? "))
futureplan = str(input("What is your future plan? "))
city = str(input("What city do you live in? "))
country = str(input("What country do you live in? "))
religion = str(input("What is your religion? "))
print("\n--- Your Information ---")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Contact: {contact}")
print(f"Degree: {degree}")
print(f"Hobby: {hobby}")
print(f"Siblings: {siblings}")
print(f"Best Friend's Name: {friendname}")
print(f"Active Course: {activecourse}")
print(f"Favorite Programming Language: {favlanguage}")
print(f"Strength: {strength}")
print(f"Weakness: {weakness}")
print(f"Business: {business}")
print(f"Favorite Food: {favoritefood}")
print(f"Favorite Subject: {favsubject}")
print(f"Career: {career}")
print(f"GPA: {gpa}")
print(f"Future Plan: {futureplan}")
print(f"City: {city}")
print(f"Country: {country}")
print(f"Religion: {religion}")
